### ISSUE TITLE
Republish package to the PyPI.

### ISSUE THREAD

**Issue by proofit404** [pythonic-emacs/service-factory#2]
I don't want to be affiliated with this package anymore.

I can't remove myself from the package administrators on PyPI.

@CeleritasCelery @dakra Please, republish the package on PyPI.

```
pip install --user twine
python setup.py sdist
twine upload dist/*
```
Thanks.

**Comment by dakra** [comment]
I think @CeleritasCelery is way more active than I'm so I think he should publish it.
But as there's an issue already, I'll wait till Monday and if it's not reuploaded by then I'll do it.

Thanks for all your work

**Comment by CeleritasCelery** [comment]
Okay I republished the package https://pypi.org/project/service-factory/0.1.6/
